# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('registration_id', models.AutoField(db_column='RegistrationID', primary_key=True, serialize=False)),
                ('deployment_sampling_feature_uuid', models.UUIDField(db_column='SamplingFeatureUUID')),
                ('authentication_token', models.CharField(db_column='AuthToken', editable=False, max_length=64)),
                ('user', models.OneToOneField(db_column='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
