# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataloaderinterface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrosharesitesetting',
            name='hs_user',
        ),
        migrations.AddField(
            model_name='hydrosharesitesetting',
            name='hs_account',
            field=models.ForeignKey(db_column='hs_account_id', default=-1, on_delete=django.db.models.deletion.CASCADE, to='dataloaderinterface.HSUAccount'),
            preserve_default=False,
        ),
    ]
