# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-13 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataloaderinterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesensor',
            name='last_measurement_id',
            field=models.IntegerField(blank=True, db_column='LastMeasurementID', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesensor',
            name='activation_date_utc_offset',
            field=models.IntegerField(blank=True, db_column='ActivationDateUtcOffset', null=True),
        ),
    ]
