# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-14 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataloaderinterface', '0002_auto_20171214_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrosharesitesetting',
            name='update_freq',
            field=models.DurationField(default='0 days', verbose_name='Update Frequency'),
        ),
    ]
