# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-18 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataloaderinterface', '0002_auto_20171218_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydroshareuser',
            old_name='scope',
            new_name='oauth_scope',
        ),
    ]
