# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-19 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataloaderinterface', '0003_auto_20171219_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrosharesitesetting',
            name='last_sync_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
