# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-18 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataloaderinterface', '0003_auto_20171218_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydroshareuser',
            name='ext_hydroshare_id',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hydroshareuser',
            name='account_nickname',
            field=models.CharField(default='Default Account', max_length=255),
        ),
    ]
