# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataloaderinterface', '0004_auto_20171219_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrosharesitesetting',
            name='hs_account',
            field=models.ForeignKey(blank=True, db_column='hs_account_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='dataloaderinterface.HSUAccount'),
        ),
    ]
