# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-21 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataloaderinterface', '0005_auto_20171220_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydroshareaccount',
            old_name='account_nickname',
            new_name='name',
        ),
    ]
